name: telegram

on: [push, workflow_dispatch]
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run min test
        id: min
        continue-on-error: true
        run: python -m unittest test.tests_functions.TestSupportingFunctions.test_min
      - name: Run max test
        id: max
        continue-on-error: true
        run: python -m unittest test.tests_functions.TestSupportingFunctions.test_max
      - name: Run sum test
        id: sum
        continue-on-error: true
        run: python -m unittest test.tests_functions.TestSupportingFunctions.test_sum
      - name: Run mult test
        id: mult
        continue-on-error: true
        run: python -m unittest test.tests_functions.TestSupportingFunctions.test_mult
        
      - name: Send report   
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            
            Unittest result:
                Function min test: ${{ steps.min.outcome }}
                Function max test: ${{ steps.max.outcome }}
                Function min test: ${{ steps.sum.outcome }}
                Function max test: ${{ steps.mult.outcome }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
