name: unittest

on: [push, workflow_dispatch]
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy my code
      - uses: actions/checkout@v3
      - name: Python install
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Start unittest
        run: python -m unittest test/tests_functions.py
